services:
  
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=course
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=movies
    ports:
      - '15432:5432'  # host:container